name: repoxlc
on:
  schedule:
    - cron: '1 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync shuye
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wuzhi01/MyActions.git"
          source_branch: "main"
          destination_branch: "cp-jd"
          github_token: ${{ secrets.PAT }}
          
      - name: sync full
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/justnew139/full.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}

      - name: sync youes
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/justnew139/youthes.git"
          source_branch: "main"
          destination_branch: "youes"
          github_token: ${{ secrets.PAT }}
